### ISSUE TITLE
Broken link to Git from bottom-up book HW1

### ISSUE THREAD

**Issue by diraulo** [saasbook/AV102#15]
Section `1.2: GIT FROM THE BOTTOM UP` has a broken link to the PDF book. 
http://ftp.newartisans.com/pub/git.from.bottom.up.pdf

**Comment by diraulo** [comment]
I just updated the link to point to the online version https://jwiegley.github.io/git-from-the-bottom-up/

**Comment by tansaku** [comment]
thanks @diraulo!
