### ISSUE TITLE
stray mentions to stack forum

### ISSUE THREAD

**Issue by bill-auger** [saasbook/AV102#18]
AV102 HW-part5 and HW-part6 still mention the forum erroneously under the SUBMIT TA WORK heading

[HW-part5](https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2015_Fall/courseware/df7b653ed6854db48e8aaef7062bf666/233fecdbd18b406e953e5eb34183cd2f/) mentions "SE post":

Please enter a hyperlink to a youtube recording, pivotal tracker bug report, SE post, or screenshot.

[HW-part6](https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2015_Fall/courseware/4a5f722906694b7bb5578a376a98ce98/937ab9021cb24a918153035202dd0759/) does not mention the forum at all:

Please enter a hyperlink to a youtube recording, pivotal tracker bug report, or screenshot.

**Comment by freeranger** [comment]
What is the correct wording we should have here?

**Comment by bill-auger** [comment]
"SE post" indicates that helping a student on the forum can be submitted as a valid HW assignment

that was written the one time we were using the stack forums instead of the internal edX forum

so if helping a student on the forum is still an acceptable homework assignment then they BOTH should read like the first example with "SE post" replaced by "edX forum post" - or else they BOTH should read like the second example

**Comment by freeranger** [comment]
Seems like we need @tansaku to confirm the wording

**Comment by idfubar** [comment]
At present the problematic language only exists as part of the 'Level 3' assignments (which may have used an old page as a template); the 'Level 2' assigments say "Respond to student in forum (chat or forum)" - which seems innocuous/generic enough...

PS:  The language could be changed by editing via edX Edge before closing this issue...

**Comment by idfubar** [comment]
Draft language ("Respond to student in a class-designated forum", w/"SE" elided) has been proposed & will be published barring additional changes...
