### ISSUE TITLE
TA Responsibilities video still has skype chat on the slides

### ISSUE THREAD

**Issue by tansaku** [saasbook/AV102#2]
Still mentions skype chat.  Skype has been replaced by slack/gitter

**Comment by tansaku** [comment]
could just edit the video to cut off at 10:39 to remove the helpdesk hangout stuff

**Comment by mach1010** [comment]
This vid has a slide that mentions helpdesk, bridged Skype, and StackExchange Forum. It is live.
https://studio.edge.edx.org/container/block-v1:AgileVentures+AV102+2015_Fall+type@vertical+block@bd6e944c6dff417e94a5e1a2b6964b43
