### ISSUE TITLE
"Level 3" progress page inconsistencies

### ISSUE THREAD

**Issue by bill-auger** [saasbook/AV102#20]
completed assignments for "Level 3" the are marked in the itemized list such as "Problem Scores:  1/1" but do not appear on the progress histogram

also - the progress histogram shows six assignments for "Level 3"

CL301 CL302 CL303 CL304 CL305 CL306

but there are only four courseware sections denoted as "level 3"

Level 3 Certificate Part 9
Level 3 Certificate Part 10
Level 3 Certificate Part 11
Level 3 Certificate Part 12

**Comment by tansaku** [comment]
hi @bill-auger - there are more level 3 components coming ... - I'll check the progress hookup ...

**Comment by tansaku** [comment]
the level 3 weren't hooked up to the progress page, but they are now - see if that fixes thing ... parts 13 and 14 will be released in the next two weeks ...

**Comment by bill-auger** [comment]
working
