### ISSUE TITLE
Label current course

### ISSUE THREAD

**Issue by joaopapereira** [saasbook/AV102#24]
We should create a label to tag the current course issues so we know what we need to work on

**Comment by tansaku** [comment]
good idea @joaopapereira - although I think all the outstanding issues from the last course apply to the current one too ..

**Comment by freeranger** [comment]
Should this issue be closed then if all issues are still applicable?
If they aren't well, the old course is gone now so they should be just deleted presumably...

**Comment by tansaku** [comment]
well the old course still exists but anyway, yes, let's close this.
