### ISSUE TITLE
Add freeranger to the staff page

### ISSUE THREAD

**Issue by freeranger** [saasbook/AV102#30]
here: 
https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2016_Spring/about

TODO: Freeranger to supply bio information and photo for the page

**Comment by freeranger** [comment]
Bio (feel free to edit):
Tony Butler is an independent IT Consultant and Software Engineer based in London with over 20 years experience in the banking and finance sectors.
He has spent the past 15 years developing web applications and supporting services primarly using C#/ASP.NET, but with an increasing focus on front end tooling and technologies - typescript, gulp, angular, signalR etc to provide richer client experiences on the web.
He is a keen advocate of agile methodologies (Scrum in particular) and test driven development, and has introduced them to a number of project teams which have relied on more traditional software development practices.
In recent times, Tony has been keen to expand his knowledge of programming languages and software development techniques and has taken a number of MOOCs across a variety of platforms, including both CS169.x courses and in the last year having taken AV102, he is a Level 3 TA for the next generation of students on those courses.
Though the power of MOOCs, he has gained experience in a variety of languges and tools including Ruby, Mongo, Meteor, Bootstrap, Ionic and Scala.
Tony enjoys learning and helping others to learn and he holds a 1st Class BSc (Honours) in Computing (including 7 distinctions).

Photo: https://onedrive.live.com/redir?resid=BD5CCEE6092DAA9!186959&authkey=!ACMT-70x0EToyS8&v=3&ithint=photo%2cJPG

**Comment by tansaku** [comment]
done https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2016_Spring/about
