### ISSUE TITLE
edX Permissions issue?

### ISSUE THREAD

**Issue by tansaku** [saasbook/AV102#32]
Tom Giordano [12:34 AM] 
> I found a very minor bug in the AV102 course pages.  Clicking the "next page" link from
https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2016_Spring/courseware/285e742a32834d6bb4824041d987f30c/
gives a Page Not Found error.

Sam Joseph [8:01 AM] 
> thanks for reporting that @justom - I can't seem to replicate it myself ... although perhaps that's an edx permissions thing - the next page after that would be the start of the next week which I don't think you have access to yet ...

**Comment by freeranger** [comment]
I have tested this in Edge Studio and it works for me too - I think this can be closed as not an issue.
