### ISSUE TITLE
Progress page shows I have completed HW1 when I have only completed HW0

### ISSUE THREAD

**Issue by freeranger** [saasbook/AV102#33]
![image](https://cloud.githubusercontent.com/assets/1401069/14887730/efcbdd6e-0d4e-11e6-9f34-b69192b38080.png)

**Comment by freeranger** [comment]
Also the tooltip fpr HW0 refers to "Homework1: HW0" which is confusing:
![image](https://cloud.githubusercontent.com/assets/1401069/14940679/12f931da-0f78-11e6-9f9e-20667fb8bd5d.png)

This applies to the other homeworks too - all out by 1.

**Comment by tansaku** [comment]
I know, it's annoying - if you have a group of HWs in edX they start numbering from 1 - I can fix this if I manually add explicit HW elements - I'll do it if I can get everything else sorted tonight for release
