### ISSUE TITLE
HW2.2 minor corrections

### ISSUE THREAD

**Issue by freeranger** [saasbook/AV102#36]
https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2016_Spring/courseware/ddc02b3285914a3fb98a658d666870ca/1c56de655ec24df8a9526d6f8487e945/

Section is titled "Setup Git on C9, Modify local file and Push to Github" but use of C9 is described as optional in the actual text...so shouldn't the title just be "Modify local file and Push to Github"

Also, in the body of the instruction itself, it says:

> You can use your own system, but it would be good to get **the C9** and do this assignment there.
> It feels like one or more words are missing there ;)

**Comment by armandofox** [comment]
FWIW, for the berkeley course we have moved to "only C9 is officially supported", so i'm in favor of making the necessary changes to convey this in the MOOC as well.  it has saved a good deal of headache for our TAs.

**Comment by freeranger** [comment]
Makes sense.  Perhaps for a future iteration, an earlier part of the homework is to actually get set up on C9

**Comment by tansaku** [comment]
yeah, gonna change this to promote C9 more strongly
