### ISSUE TITLE
Week 2 managing chores - wording

### ISSUE THREAD

**Issue by freeranger** [saasbook/AV102#38]
https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2016_Spring/courseware/ddc02b3285914a3fb98a658d666870ca/368c4a1add394207a3e1fbc120f551da/

> Choose the most true statement.

Seems poorly worded IMO - something is either true or false, not "a little bit true" or "mostly false"

Alternative wording could be:
- Which statement is true about chores or
- Choose the most accurate statement

**Comment by tansaku** [comment]
updated

**Comment by freeranger** [comment]
@tansaku, a couple of more on this:

> Which **is** statement is not false?
> and
> Chores are always easier than development of a feature to support a user **storie**.

**Comment by tansaku** [comment]
thanks - fixed
