### ISSUE TITLE
Week 2 Version control quiz

### ISSUE THREAD

**Issue by freeranger** [saasbook/AV102#39]
https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2016_Spring/courseware/ddc02b3285914a3fb98a658d666870ca/06a6852d47684a7587a2c2af7cc3888f/

The answers here are multiple choice but you are only supposed to pick one - should they be radio buttons instead?

**Comment by tansaku** [comment]
have adjusted the wording

**Comment by freeranger** [comment]
@tansaku the wording now says:

> Which are NOT a reason to use version control?
> 
> Select the answers that matche

Possibly should be "Which one(s) are NOT.." and definitely shouldn't be "matche" ;)

**Comment by tansaku** [comment]
adjusted
