### ISSUE TITLE
Check automated transcripts for all videos

### ISSUE THREAD

**Issue by tansaku** [saasbook/AV102#4]
YouTube has now quite good support for updating the transcript of videos - we could be taking passes through to update?

**Comment by freeranger** [comment]
If you are going to work on a video, put your name against it so nobody else starts on it and then tick it off once done
- [x] Week 0: Overview  - @freeranger
- [x] Week 0: What is this course about - @freeranger
- [x] Week 1: TA Prerequisites, Role and Importance - @freeranger
- [x] Week 1: What are the TA's Responsibilities - @freeranger
- [x] Week 1: The Benefits of Being a TA - @freeranger
- [x] Week 2: Overview of Distributed Software Development @tansaku
- [x] Week 2: User Stories Introduction @tansaku
- [x] Week 2: Managing Chores @tansaku
- [x] Week 2: Acceptance/Unit Test Cycle @tansaku
- [x] Week 2: What is Version Control? @tansaku
- [x] Week 2: Deploying to the Cloud @tansaku
- [x]  Week 2: Spiking @tansaku
- [x] Week 3: Overview of Distributed Team Management  @tansaku
- [x] Week 3: Agile & Distributed Agile @tansaku
- [x] Week 3: Scrum @tansaku
- [x] Week 3: Daily Scrum @tansaku
- [x] Week 3: Sprint Review Event @tansaku
- [x] Week 3: Sprint Retrospective Event - an hour! might need a few people on this! @tansaku
- [x] Week 3: Distributed Project Management Tools @tansaku
- [x] Week 3: Pair Programming @tansaku
- [x] Week 3: Does Pair Programming have to suck?  @tansaku
- [x] Week 3: Pairing is Caring @tansaku
- [x] Week 3: Pair Programming Advice from NC State University @tansaku
- [x] Week 3: Github Pong @tansaku
- [x] Week 3: Github Pong Example - 1hr 21 - again, might need a few people on it! @tansaku
- [x] Week 3: Github for Teams @tansaku
- [x] Week 4: Overview of Communication and Breakdowns @tansaku
- [x] Week 4: Communicating Effectively in Online Forums @tansaku
- [x] Week 4: Bugs and Debugging @tansaku
- [x] Week 4: Creating AV Events and Hangouts @tansaku
- [x] Week 4: Recording Live Sessions @tansaku
- [x] Week 4: EdX Forum and WrapUp @tansaku

**Comment by freeranger** [comment]
Some of them - I have pointed out the "worst offenders" are pretty big - and are actual sessions from Agile Ventures - perhaps they shouldn't be tackled because "in real life" they wouldn't be on AV and also because they are massive?
Or at least prioritise them (and other AV videos) last, behind the actual taught content.

**Comment by tansaku** [comment]
@freeranger I'm taking the lead on everything here - I think I've got a serious headstart on everyone trying to understand my own mumbling :-)

**Comment by tansaku** [comment]
I think if anyone has got any spare transcribing time it should probably go into the 169 vids ...
