### ISSUE TITLE
Week 2 Deloying to the cloud quiz - not enough buttons?

### ISSUE THREAD

**Issue by freeranger** [saasbook/AV102#40]
https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2016_Spring/courseware/ddc02b3285914a3fb98a658d666870ca/1e8e9d26afc447a994bc7bbd4bc00343/

There are two questions, each with two correct answers, but there are only 2 points up for grabs in total, and there is only one set of Check/Show Answer buttons - is this correct?  It seems inconsistent with the other quizzes where you get buttons for each question rather than them being grouped

**Comment by tansaku** [comment]
broken into two questions
