### ISSUE TITLE
W4 - Creating AV Events and Hangouts Practice quiz

### ISSUE THREAD

**Issue by freeranger** [saasbook/AV102#41]
1. The title of this quiz is "Checkboxes" which seems incorrect.
2. The question is "Which are needed to make a Hangout event video with others?" but "Webcam" is not one of the accepted answers.
   Whilst you can have audio only feeds, the question is specifically about a _video_ feed so I'd have thought a webcam (or some sort of cam anyway) would be essential to that.

**Comment by tansaku** [comment]
Thanks @freeranger - I've updated the title and various of the language which was all a bit non-native.

A webcam is not required however.  The critical thing about making a coding video is the screenshare - no webcam required ...
