### ISSUE TITLE
Staff badges in the forums

### ISSUE THREAD

**Issue by freeranger** [saasbook/AV102#42]
@tansaku neither you nor I appear as staff in the eDx edge forums.  I suspect nobody else does either but I haven't seen any posts from them ;)

**Comment by tansaku** [comment]
thanks @freeranger - I think I fixed that - wish edX would automatically add staff to have badges but there's an extra manual step ...

**Comment by freeranger** [comment]
@tansaku Is it fixed?  maybe.  There are certainly badges now.
I am listed as a "Community TA" but I am also a member of staff (or at least I'm on the staff page) so maybe I should be "staff" in the forums too?
OTOH I don't have "Staff" access to everything (e.g. adding people to PT) so maybe I'm not really staff and staying "Community TA" is more appropriate?  #identitycrisis :}

**Comment by tansaku** [comment]
I made you a moderator - does that help? :-)

**Comment by freeranger** [comment]
@tansaku I don't mind what I am as long as I am what you think I should be :)
