### ISSUE TITLE
WK0 courseware - duplicate headings

### ISSUE THREAD

**Issue by bill-auger** [saasbook/AV102#45]
also the same on the next accordian tab "What is This Course About? (4:51)"

![av102-scrot](https://cloud.githubusercontent.com/assets/1642691/24831576/50b2cdf6-1c6a-11e7-93cf-668ca7c3b1c1.png)

**Comment by tansaku** [comment]
name of video and sub-section are same - have adjusted slightly ...

![adjusted text](https://www.dropbox.com/s/5iglcbei02548ec/Screenshot%202017-04-10%2009.15.30.png?dl=1)

**Comment by bill-auger** [comment]
ok i see now it looked the same last run

i see the intention now - it echoes the tip of the breadcrumbs heading above the accordion

chalk it of as another edX UI quirk
