### ISSUE TITLE
Week 1 Video/Slide/Transcript Inconsistency "Who are TA's and why do we need you?"

### ISSUE THREAD

**Issue by robmullr** [saasbook/AV102#47]
During the video "Who are TA's and why do we need you?", at the 1:00 mark, the slides and transcript both say "preferably a few hours a week" but the audio says "preferably a few hours a day".

**Comment by tansaku** [comment]
thanks for catching that - videos are annoyingly time consuming to fix ... I really appreciate how sensible it is to break them into multiple chunks of only a few minutes each now ...

**Comment by idfubar** [comment]
Fixed.

https://github.com/saasbook/AV102/pull/54
