### ISSUE TITLE
Week 2 HW 1.3 GitHub Account Instructions

### ISSUE THREAD

**Issue by robmullr** [saasbook/AV102#49]
HW 2.1 has text explaining how to get a GitHub account but we are using GitHub for HW 1.3.  Shouldn't this text be moved/copied to 1.3?

**Comment by tansaku** [comment]
@robmullr do you mean 1.3 or 2.3?

**Comment by robmullr** [comment]
Week 2 HW 1.3 directs them to do the git immersion tutorial.  Seems to me
they should establish a github account at that point.  HW 2.1 then gives
the instructions.

**Comment by tansaku** [comment]
@robmullr right - but does the git immersion tutorial require github?  I don't think it does as Github is listed in the future topics:

http://gitimmersion.com/lab_52.html

**Comment by idfubar** [comment]
https://github.com/saasbook/AV102/issues/50
