### ISSUE TITLE
Update Homework 1 instructions - Section 2.2

### ISSUE THREAD

**Issue by diraulo** [saasbook/AV102#5]
Section 2.2 still suggests the student use a copy of the VM which has not been updated in a while now.
The link to the VM instructions points to the old version of the site (beta.saasbook.info)

Shouldn't this be updated for use with Cloud9?

Also not sure if that's the intended due date for the assignment but it currently says Oct 13th

**Comment by tansaku** [comment]
yes that all needs updated - it's not released to the students yet, but you can see it as you are on the course staff

**Comment by freeranger** [comment]
@tansaku I think this ticket can be closed as HW1 is completely different now...
