### ISSUE TITLE
Week 4 HW 4 Use the edX forum link

### ISSUE THREAD

**Issue by robmullr** [saasbook/AV102#51]
When I click the link to the edX Forum, it leads to https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2016_Spring/about. It should point to https://edge.edx.org/courses/course-v1:AgileVentures+AV102+Spring_2017/wiki/AgileVentures.AV102.2015_Fall/

**Comment by tansaku** [comment]
thanks for reporting this @robmullr - I'll try to find that link - can you tell me where you found it?

**Comment by tansaku** [comment]
ah I think I found it - in next week's homework right? https://edge.edx.org/courses/course-v1:AgileVentures+AV102+Spring_2017/courseware/d5ae867ba98a4dd6be3a68fa0a6ea98d/044b87bdfbe04857b975aeab2c6956d6/

**Comment by idfubar** [comment]
Fixed.

(Similar to 'https://github.com/saasbook/AV102/issues/46' - but arguably a feature & not a bug...)
