### ISSUE TITLE
Week 3. Communicating Effectively in Online Forums. Time listed in sidebar [27:02] does not match length of video [13:44]

### ISSUE THREAD

**Issue by brudgers** [saasbook/AV102#64]
Week 3. Communicating Effectively in Online Forums. Time listed in sidebar [27:02] does not match length of video [13:44]

**Comment by idfubar** [comment]
Week 4 Communicating Effectively in Online Forums is 27:02 (so length in sidebar == sum of week's required videos, 13:44 + 13:18...?)

PS:  Please note issue/week mismatch...
