### ISSUE TITLE
transcript for chores video looks wrong

### ISSUE THREAD

**Issue by tansaku** [saasbook/AV102#88]
https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2017_Fall/courseware/ddc02b3285914a3fb98a658d666870ca/368c4a1add394207a3e1fbc120f551da/?child=first

**Comment by idfubar** [comment]
Yes, correct; just fixed it... but the pull request (for the transcript file) should be reviewed - as the desired format for files kept in the repository wasn't entirely clear (i.e. whether edX timed transcript files, YouTube 'cue sheets', or the "scripts" likely used when creating the videos was desired).

PS:  The transcript accompanying the video on YouTube was the source for 'https://github.com/saasbook/AV102/pull/58' (i.e. the copy submitted without timestamps) - but, as the AV102 repository didn't have an existing file for the transcripts after Week 2, it never made its way into the copy used in the courseware (as edit access for the course was provided after the pull requests were submitted - but before a final "decision" about how best to maintain the transcripts going forward)...

**Comment by idfubar** [comment]
Also - as mentioned in the pull request notes - there is a *huge* difference between the 'English (United States)' & 'English (United Kingdom)' transcriptions for a given video - painful lesson learned!!

= D

**Comment by idfubar** [comment]
Creating a separate folder for WebVTT format copies of the transcripts (allowing for revisions to be downloaded/uploaded as needed to edX Studio & captions to be used for future revisions)...
