### ISSUE TITLE
our Wiki links to /about 

### ISSUE THREAD

**Issue by mattwr18** [saasbook/AV102#93]
On the wiki page of the edx course there is an add article button that leads to this URL, https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2018_Summer/wiki/AgileVentures.AV102.2015_Fall/_create/, which seems to create an article for the 2015 Fall MOOC.

**Comment by tansaku** [comment]
yeah, basically so we can have a shared wiki across all instances of the class and folks can see part assignment submissions :-)
